b2b sample with nextjs
caos/zitadel-examples pull request #44
Opened 2021-11-11 11:51 UTC by peintnermax

2021-11-11 13:54 UTC, mffap requested changes

2021-11-11 13:54 UTC, mffap commented on b2b-nextjs/README.md
> +This is a demo showcasing the use of B2B (Business to Business).
```suggestion
This is a demo showcasing how you can use ZITADEL in a B2B (Business-to-Business) context, where a company is providing a customer portal to their customers:

- A user of the customer should see all granted projects in the portal
- A admin user of the customers sees a list of customer's users (could be expanded to make roles editable)

```

2021-11-11 13:54 UTC, mffap commented on b2b-nextjs/README.md
> +On the detail page, add a new Key, set an optional expiration date and download the generated JSON file.
```suggestion
On the detail page, add a new key, set an optional expiration date and download the generated JSON file.
```

2021-11-11 13:54 UTC, mffap commented on b2b-nextjs/README.md
> +Select `owned project`, search for `B2B-Demo` and select `PROJECT_OWNER_VIEWER` as the Management role.
```suggestion
Select `owned project`, search for `B2B-Demo` and select `PROJECT_OWNER_VIEWER` as the management role.
```

2021-11-11 13:54 UTC, mffap commented on b2b-nextjs/README.md
> +Now make sure to enable `Assert Roles on Authentication` above the role table. This makes sure that roles are set in your OIDC ID Token which is used by the application to enable UI components.
```suggestion
Now make sure to enable `Assert Roles on Authentication` above the role table. This makes sure that roles, which is used by the application to enable UI components, are set in your OIDC ID Token.
```

2021-11-11 13:57 UTC, fforootd commented on b2b-nextjs/README.md
> +ZITADEL_CLIENT_ID=129954167266602411@portal
```suggestion
ZITADEL_CLIENT_ID={YourClientID}
```

2021-11-11 13:57 UTC, fforootd commented on b2b-nextjs/README.md
> +SERVICE_ACCOUNT_SECRET=
```suggestion
SERVICE_ACCOUNT_SECRET={YourServiceAccountSecret}
```

2021-11-11 14:07 UTC, mffap commented
```
[next-auth][error][oauth_callback_error]
https://next-auth.js.org/errors#oauth_callback_error undefined {
  statusCode: 400,
  data: '{"error":"invalid_request","error_description":"code missing"}\n'
}
```
@peintnermax Ich hab die .env.local aus dem anderen Beispiel rüberkopiert. Wenn ich auf Sign-in klicke, dann bekomm ich den Fehler oben (also im Terminal)

2021-11-11 14:27 UTC, peintnermax commented
hab noch ein paar sachen ausgebessert.. 
hast du das file im folder, b2b-nextjs?

2021-11-11 14:38 UTC, mffap approved these changes

2021-11-11 14:45 UTC, mffap commented
@ulritter this is the demo example of a b2b-portal

2021-11-12 07:22 UTC, merged

2021-11-12 07:59 UTC, ulritter commented
Great, thanks for adding me!